### ISSUE TITLE
add new game

### ISSUE THREAD

**Issue by MaskDuck** [advaith1/activities#39]
i just found a new game called putt party with the spec below
![image](https://user-images.githubusercontent.com/70831061/154828655-2f872d3b-7343-49ce-933a-1e4a7620a2d2.png)
and with the id `910224161476083792`
can you add it pleaaaasssseeeeeee? <3

**Comment by MaskDuck** [comment]
or maybe allow us to start game with custom app id idk

**Comment by advaith1** [comment]
I already know about putt party; it isn't released yet so it can't be opened. Requesting new games is pretty pointless because I already know about all of them and I add new games as they get released.

The bot has all of the usable activities so custom app id support would not be useful, and it can't be implemented with good ux anyway.
